In [10]:
! pip install opencv-python

In [11]:
import zipfile
import os
import cv2
import numpy as np
import pandas as pd

In [12]:
 folder = r"F:\archive.zip"

In [13]:
file_path = r"F:\Digit Images"
with zipfile.ZipFile(folder,'r') as file:
   file.extractall(file_path)

os.getcwd()

os.chdir(file_path)

os.listdir()

os.getcwd()+'\\'+'dataset'

original = os.getcwd()+'\\'+'dataset'
os.chdir(original)

In [14]:
os.getcwd()

'F:\\Digit Images\\dataset'

In [15]:
os.listdir()

['Beagle',
 'Boxer',
 'Bulldog',
 'Dachshund',
 'German_Shepherd',
 'Golden_Retriever',
 'Labrador_Retriever',
 'Poodle',
 'Rottweiler',
 'Yorkshire_Terrier']

In [16]:
folder = r"F:\dataset"
os.getcwd()
os.chdir(folder)
Rows = []
label = []
for i in os.listdir():
    path = folder+'\\'+i
    os.chdir(path)
    for j in os.listdir():
       array = cv2.imread(j,0)
       resized = np.resize(array,(150,150))
       row = resized.flatten()
       Rows.append(row)
       label.append(i)

In [17]:
Rows

[array([ 0,  1,  4, ..., 24, 25, 25], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([183, 186, 181, ..., 155, 154, 154], dtype=uint8),
 array([217, 218, 220, ..., 148, 146, 146], dtype=uint8),
 array([155, 154, 156, ..., 145, 141, 138], dtype=uint8),
 array([ 81,  83,  85, ..., 127, 138, 149], dtype=uint8),
 array([ 81,  86,  90, ..., 118, 102, 127], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([183, 186, 181, ..., 155, 154, 154], dtype=uint8),
 array([ 38,  43,  49, ..., 140, 137, 134], dtype=uint8),
 array([189, 189, 189, ..., 108, 129, 120], dtype=uint8),
 array([225, 226, 229, ...,  42,  39,  37], dtype=uint8),
 array([188, 223, 192, ..., 185, 172, 172], dtype=uint8),
 array([181, 181, 181, ..., 194, 193, 193], dtype=uint8),
 array([  0,   0,   0, ..., 140, 140, 140], dtype=uint8),
 array([ 0,  1,  4, ..., 24, 25, 25], dtype=uint8),
 array([188, 223, 192, ..., 185, 172, 172], dtype=uint8),
 array([120, 120, 120, ...

In [ ]:
df1 = pd.DataFrame(Rows)


In [19]:
df1

0      1      2      3      4      5      6      7      8      9      \
0        0      1      4      9     13     18     21     24      8      7   
1      255    255    255    255    255    255    255    255    255    255   
2      183    186    181    163    138    110     82     63     68     68   
3      217    218    220    221    224    225    227    228    232    233   
4      155    154    156    163    172    178    179    177    180    179   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
962     19     18     17     15     14     14     14     14     28     37   
963    255    255    255    255    255    255    255    255    255    255   
964     80     80     79     77     76     75     73     73     72     71   
965     63     63     64     64     65     66     67     67     69     69   
966     94     91     85     79     75     78     84     90     84     85   

     ...  22490  22491  22492  22493  22494  22495  22496  22497  22498  22499  
0    ...     30     31     28     25     21     20     22     24     25     25  
1    ...    255    255    255    255    255    255    255    255    255    255  
2    ...    176    176    176    172    167    162    157    155    154    154  
3    ...    137    140    151    155    158    157    153    148    146    146  
4    ...    152    161    168    164    162    170    149    145    141    138  
..   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
962  ...    237    237    237    237    237    237    237    236    236    236  
963  ...    255    255    255    255    255    255    255    255    255    255  
964  ...    112    113    113    113    113    113    113    113    114    114  
965  ...    124     77    117    125     96    115    103     78     62     57  
966  ...    174    187    117    123    126    126    129    134    132    125  

[967 rows x 22500 columns]

In [20]:
df2 = pd.DataFrame(label,columns = ['Digit'])
df2

Digit
0               Beagle
1               Beagle
2               Beagle
3               Beagle
4               Beagle
..                 ...
962  Yorkshire_Terrier
963  Yorkshire_Terrier
964  Yorkshire_Terrier
965  Yorkshire_Terrier
966  Yorkshire_Terrier

[967 rows x 1 columns]

In [21]:
df = pd.concat([df1,df2],axis=1)

In [22]:
df

0    1    2    3    4    5    6    7    8    9  ...  22491  22492  \
0      0    1    4    9   13   18   21   24    8    7  ...     31     28   
1    255  255  255  255  255  255  255  255  255  255  ...    255    255   
2    183  186  181  163  138  110   82   63   68   68  ...    176    176   
3    217  218  220  221  224  225  227  228  232  233  ...    140    151   
4    155  154  156  163  172  178  179  177  180  179  ...    161    168   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
962   19   18   17   15   14   14   14   14   28   37  ...    237    237   
963  255  255  255  255  255  255  255  255  255  255  ...    255    255   
964   80   80   79   77   76   75   73   73   72   71  ...    113    113   
965   63   63   64   64   65   66   67   67   69   69  ...     77    117   
966   94   91   85   79   75   78   84   90   84   85  ...    187    117   

     22493  22494  22495  22496  22497  22498  22499              Digit  
0       25     21     20     22     24     25     25             Beagle  
1      255    255    255    255    255    255    255             Beagle  
2      172    167    162    157    155    154    154             Beagle  
3      155    158    157    153    148    146    146             Beagle  
4      164    162    170    149    145    141    138             Beagle  
..     ...    ...    ...    ...    ...    ...    ...                ...  
962    237    237    237    237    236    236    236  Yorkshire_Terrier  
963    255    255    255    255    255    255    255  Yorkshire_Terrier  
964    113    113    113    113    113    114    114  Yorkshire_Terrier  
965    125     96    115    103     78     62     57  Yorkshire_Terrier  
966    123    126    126    129    134    132    125  Yorkshire_Terrier  

[967 rows x 22501 columns]

# Model Building

In [23]:
X=df.drop('Digit',axis=1)
y=df['Digit']

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.8,random_state=23)

# KNN

In [26]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
knn = KNeighborsClassifier()
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
accuracy_score(y_test,y_pred)

0.2532299741602067

# Decision tree

In [27]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)
y_pred = dt.predict(X_test)
accuracy_score(y_test,y_pred)

0.6227390180878553

# LogisticRegression

In [28]:
from sklearn.linear_model import LogisticRegression
lr= LogisticRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
accuracy_score(y_test,y_pred)

0.6317829457364341

# pickel

In [29]:
import pickle

In [30]:
pickle.dump(lr,open(r"F:\Digit Images\model.pkl",'wb'))

In [31]:
model = pickle.load(open(r"F:\Digit Images\model.pkl",'rb'))

In [32]:
def img_data(i_i):
    array = cv2.imread(i_i,0)
    resized = np.resize(array,(150,150))
    row = resized.flatten()
    return row

model.predict([img_data(r"F:\Digit Images\dataset\Beagle\Beagle_10.jpg")])[s0s]

NameError: name 's0s' is not defined

In [ ]:
from sklearn.naive_bayes import GaussianNB
mnb= GaussianNB()
mnb.fit(X_train,y_train)
y_pred = mnb.predict(X_test)
accuracy_score(y_test,y_pred)